apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: railway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: web
