apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: railway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: edge
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: edge
