apiVersion: v1
kind: Service
metadata:
  name: raildbsetup
  namespace: railway
  labels:
    app: raildbsetup
spec:
  type: ClusterIP
  selector:
    app: raildbsetup
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
