apiVersion: v1
kind: Service
metadata:
  name: raildbsetup-service
  namespace: railway
  labels:
    app.kubernetes.io/name: raildbsetup
    app.kubernetes.io/component: setup
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: raildbsetup
    app.kubernetes.io/component: setup
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
