apiVersion: v1
kind: Service
metadata:
  name: raildatacollector
  namespace: railway
  labels:
    app.kubernetes.io/name: raildatacollector
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: raildatacollector
    app.kubernetes.io/component: collector
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
